# Generated by Django 3.2.15 on 2022-09-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('date', models.DateField(verbose_name='Data')),
                ('address', models.CharField(max_length=255, verbose_name='Endereço')),
                ('city', models.CharField(max_length=255, verbose_name='Cidade')),
                ('state', models.CharField(max_length=255, verbose_name='Estado')),
                ('zip_code', models.CharField(max_length=15, verbose_name='CEP')),
            ],
            options={
                'verbose_name': 'Leilão',
                'verbose_name_plural': 'Leilões',
            },
        ),
    ]
