# Generated by Django 3.2.15 on 2022-09-26 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('vehicle_type', models.CharField(max_length=255, verbose_name='Tipo de veículo')),
                ('initial_bid', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Lance inicial')),
                ('origin', models.CharField(max_length=255, verbose_name='Origem')),
                ('mileage', models.IntegerField(verbose_name='Quilometragem')),
                ('plate', models.CharField(max_length=7, verbose_name='Placa')),
                ('transmission', models.CharField(max_length=255, verbose_name='Câmbio')),
                ('brand', models.CharField(max_length=255, verbose_name='Marca')),
                ('model', models.CharField(max_length=255, verbose_name='Modelo')),
                ('year', models.IntegerField(verbose_name='Ano')),
                ('fuel', models.CharField(max_length=255, verbose_name='Combustível')),
                ('observation', models.TextField(verbose_name='Observações')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.auction', verbose_name='Leilão')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('property_type', models.CharField(max_length=255, verbose_name='Tipo de imóvel')),
                ('initial_bid', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Lance inicial')),
                ('origin', models.CharField(max_length=255, verbose_name='Origem')),
                ('status', models.CharField(max_length=255, verbose_name='Situação')),
                ('area', models.FloatField(verbose_name='Área')),
                ('debtis', models.BooleanField(verbose_name='Há débitos')),
                ('observation', models.TextField(verbose_name='Observações')),
                ('address', models.CharField(max_length=255, verbose_name='Endereço')),
                ('city', models.CharField(max_length=255, verbose_name='Cidade')),
                ('state', models.CharField(max_length=255, verbose_name='Estado')),
                ('zip_code', models.CharField(max_length=15, verbose_name='CEP')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.auction', verbose_name='Leilão')),
            ],
            options={
                'verbose_name': 'Imóvel',
                'verbose_name_plural': 'Imóveis',
            },
        ),
    ]
