# Generated by Django 3.2.15 on 2022-09-26 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_property_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('cnpj', models.CharField(max_length=14, unique=True, verbose_name='CNPJ')),
            ],
            options={
                'verbose_name': 'Instituição Financeira',
                'verbose_name_plural': 'Instituições Financeiras',
            },
        ),
        migrations.AddField(
            model_name='auction',
            name='bank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='auctions.bank', verbose_name='Instituição Financeira'),
            preserve_default=False,
        ),
    ]
