# Generated by Django 3.2.15 on 2022-09-26 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auctions', '0003_auto_20220926_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles_Bids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('value', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Lance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.vehicle', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Lance - Veículo',
                'verbose_name_plural': 'Lances - Veículos',
            },
        ),
        migrations.CreateModel(
            name='Properties_Bids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('value', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Lance')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.property', verbose_name='Imóvel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Lance - Imóvel',
                'verbose_name_plural': 'Lances - Imóveis',
            },
        ),
    ]
