# Generated by Django 3.2.15 on 2022-09-26 20:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auctions', '0004_properties_bids_vehicles_bids'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bids',
            field=models.ManyToManyField(blank=True, through='auctions.Properties_Bids', to=settings.AUTH_USER_MODEL, verbose_name='Lances'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='bids',
            field=models.ManyToManyField(blank=True, through='auctions.Vehicles_Bids', to=settings.AUTH_USER_MODEL, verbose_name='Lances'),
        ),
    ]
