# Generated by Django 3.2.15 on 2022-09-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20220926_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='minimum_increment',
            field=models.IntegerField(default=1, verbose_name='Incremento Mínimo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='minimum_increment',
            field=models.IntegerField(default=1, verbose_name='Incremento Mínimo'),
            preserve_default=False,
        ),
    ]
