# Generated by Django 3.2.15 on 2022-09-28 14:36

from django.db import migrations, models
import django.db.models.deletion
import youtan_auctions.auctions.utils


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20220927_1643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='properties_bids',
            options={'ordering': ['-id'], 'verbose_name': 'Lance - Imóvel', 'verbose_name_plural': 'Lances - Imóveis'},
        ),
        migrations.AlterModelOptions(
            name='vehicles_bids',
            options={'ordering': ['-id'], 'verbose_name': 'Lance - Veículo', 'verbose_name_plural': 'Lances - Veículos'},
        ),
        migrations.CreateModel(
            name='VehicleImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=youtan_auctions.auctions.utils.get_image_path, verbose_name='Imagem')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.vehicle', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Imagem - Veículo',
                'verbose_name_plural': 'Imagens - Veículos',
            },
        ),
        migrations.CreateModel(
            name='PropertyImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=youtan_auctions.auctions.utils.get_image_path, verbose_name='Imagem')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.property', verbose_name='Imóvel')),
            ],
            options={
                'verbose_name': 'Imagem - Imóvel',
                'verbose_name_plural': 'Imagens - Imóveis',
            },
        ),
    ]
